parameters:
  commitid: ''
  state: ''
  description: ''
  path: ''

steps:
- script: 'echo ''{"state":"${{ parameters.state }}","description":"${{ parameters.description }}","context":"${{ parameters.path }}"}'''
  displayName: 'DEBUG - Github status check post body'
- script: |
    curl -L \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $(GitHubChecksPAT)" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/repos/${{ parameters.path }}/statuses/${{ parameters.commitid }} \
      -d \
      '{"state":"${{ parameters.state }}","description":"${{ parameters.description }}","context":"${{ parameters.path }}"}' \
      --fail
  displayName: 'GitHub Status check REST API call'